### ISSUE TITLE
Unexpected Error when evaluating Plugin

### ISSUE THREAD

**Issue by bicarbon8** [mtanda/grafana-aws-athena-datasource#14]
Running Grafana version 6.7.3 locally in Docker and extracted the contents of the 1.1.5 Release .zip to the plugins/datasource directory and restarted Grafana. The Plugin successfully displays in the list of Datasources, but the following error is displayed when attempting to create a new Datasource with this Plugin:
`Unexpected token '<' Evaluating http://localhost:3000/public/app/plugins/datasource/mtanda-aws-athena-datasource/module Loading app/plugins/datasource/mtanda-aws-athena-datasource/module`
see below for example directory structure on local Grafana instance following extraction of Plugin to image:
```
/usr/share/grafana/public/app/plugins $ cd datasource/
/usr/share/grafana/public/app/plugins/datasource $ ls
cloudwatch                        influxdb                          mysql
dashboard                         input                             opentsdb
elasticsearch                     loki                              postgres
grafana                           mixed                             prometheus
grafana-azure-monitor-datasource  mssql                             stackdriver
graphite                          mtanda-aws-athena-datasource      testdata
/usr/share/grafana/public/app/plugins/datasource $ cd mssql/
/usr/share/grafana/public/app/plugins/datasource/mssql $ ls
README.md           img                 plugin.json         specs
config_ctrl.ts      module.ts           query_ctrl.ts       types.ts
datasource.ts       partials            response_parser.ts
/usr/share/grafana/public/app/plugins/datasource/mssql $ cd ../mtanda-aws-athena-datasource/
/usr/share/grafana/public/app/plugins/datasource/mtanda-aws-athena-datasource $ ls
LICENSE                         aws-athena-plugin_linux_amd64   plugin.json
README.md                       config.html                     query.editor.html
aws-athena-plugin_darwin_amd64  module.js
/usr/share/grafana/public/app/plugins/datasource/mtanda-aws-athena-datasource $
```

**Comment by mtanda** [comment]
The install location is not correct😓
You should install plugin to plugins path.
https://grafana.com/docs/grafana/latest/installation/configuration/#plugins

I don't know official way to add plugin to Docker, please adjust the install location by yourself.

**Comment by bicarbon8** [comment]
as of the reported version, the location was correct. Now, as of Grafana version 7.0.2, the location has changed. Can you please advise on the expected installation process / location? Also, can you please confirm compatibility with the latest version of Grafana? Thanks in advance
