### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by mthota15** [mtanda/grafana-aws-athena-datasource#2]
Can you provide instructions on how to setup this datasource with grafana?

**Comment by roman-vynar** [comment]
Bump :)

**Comment by mtanda** [comment]
Sorry, I don't know standard way.
I just git clone to plugin directory and restart grafana-server.

```
git clone --depth 1 https://github.com/mtanda/grafana-aws-athena-datasource.git /var/lib/grafana/plugins/grafana-aws-athena-datasource
```

**Comment by anandtripathi5** [comment]
How to use this plugin will be more helpful like how to create a dashboard with this

**Comment by tonikujanpaa** [comment]
This will do the trick
`docker run -e "GF_INSTALL_PLUGINS=https://github.com/mtanda/grafana-aws-athena-datasource/releases/download/1.1.4/grafana-aws-athena-datasource-1.1.4.zip;grafana-aws-athena-datasource" -p 127.0.0.1:3000:3000 grafana/grafana`

**Comment by sudhirjena** [comment]
The correct way to install (if ubuntu) is:
`sudo -u grafana grafana-cli --pluginUrl https://github.com/mtanda/grafana-aws-athena-datasource/releases/download/1.1.4/grafana-aws-athena-datasource-1.1.4.zip plugins install grafana-aws-athena-datasource`

Check for newer release versions > 1.1.4 on https://github.com/mtanda/grafana-aws-athena-datasource/releases and substitute `1.1.4` in command above with the release version you want.

**Comment by lanecm** [comment]
I'm getting the following error when trying to use the plugin have installing it via CLI:
```
AWS Athena datasource plugin failed
Error: Fetch error: 404 Instantiating 
https://grafana.<domain>.com/public/@grafana/data 
Loading https://grafana.<domain>.com/public/plugins/mtanda-aws-athena-datasource/module.js 
Loading plugins/mtanda-aws-athena-datasource/module
```
Any ideas what I need to do to fix? I did not see the datasource plugin `/usr/share/grafana/public`.

**Comment by yunw** [comment]
> The correct way to install (if ubuntu) is:
> `sudo -u grafana grafana-cli --pluginUrl https://github.com/mtanda/grafana-aws-athena-datasource/releases/download/1.1.4/grafana-aws-athena-datasource-1.1.4.zip plugins install grafana-aws-athena-datasource`
> 
> Check for newer release versions > 1.1.4 on https://github.com/mtanda/grafana-aws-athena-datasource/releases and substitute `1.1.4` in command above with the release version you want.

I am able to install but grafana not able to load with the error:

Error: Fetch error: 404 Not Found Instantiating http://grafanahost/public/plugins/mtanda-aws-athena-datasource/module.js Loading plugins/mtanda-aws-athena-datasource/module
Data Source Error

**Comment by yunw** [comment]
> I am able to install but grafana not able to load with the error:
> 
> Error: Fetch error: 404 Not Found Instantiating http://grafanahost/public/plugins/mtanda-aws-athena-datasource/module.js Loading plugins/mtanda-aws-athena-datasource/module
> Data Source Error

I got it fixed now by using 1.1.4

**Comment by mtanda** [comment]
Thanks for testing setup.
I use grafana plugin sdk now, so setup should be easy now.

**Comment by aqt01** [comment]
No results

Tried:
`sudo -u grafana grafana-cli --pluginUrl https://github.com/mtanda/grafana-aws-athena-datasource/releases/download/1.1.4/grafana-aws-athena-datasource-1.1.4.zip plugins install grafana-aws-athena-datasource`

And also tested with latest version `2.2.7` and i don't see the plugin in plugin list

But it's being shown when i use the command: 
`grafana-cli plugins ls`

`
installed plugins:
mtanda-aws-athena-datasource @ 2.2.7
`
