### ISSUE TITLE
NoCredentialProviders error

### ISSUE THREAD

**Issue by diegoep** [mtanda/grafana-aws-athena-datasource#3]
Hi,
I've installed the plugin, but when I tried to create a panel to query the AWS Athena Data source, I received the following message: 
"NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors"

During the plugin configuration, there is no option to provide the Amazon credentials. I have tried to put a AWS "credentials" file in  ~/.aws/credentials or  /usr/share/grafana/.aws/credentials, but the error the message persists. I also tried to create a ~/.aws/config file containing the information about the region, or even add environment variables to provide access key and secret, but unfortunately, it didn't work as well.

I'm using Grafana v6.0.0. Thanks.

**Comment by mtanda** [comment]
@diegoep I update plugin.
You can set access id/key in datasource config page.
Please try :-)
