### ISSUE TITLE
should set scan data limit

### ISSUE THREAD

**Issue by kuldeep-wunder** [mtanda/grafana-aws-athena-datasource#36]
I am getting this error: 
"should set scan data limit" 

Whats the possible reason?

I can execute the query successfully in Athena but facing this issue on Grafana.
I even tried query with setting limit 10;
<img width="328" alt="Screenshot 2020-08-11 at 9 37 36 PM" src="https://user-images.githubusercontent.com/67585161/89921092-e2c45700-dc1a-11ea-8be6-1f1b6a815e4a.png">

**Comment by kuldeep-wunder** [comment]
found the issue

**Comment by 0xOllie** [comment]
@kuldeep-wunder could you please post your fix to the issue here

**Comment by 0xOllie** [comment]
After doing some research this issue is caused by the Athena workgroup query limits.
https://docs.aws.amazon.com/athena/latest/ug/workgroups-setting-control-limits-cloudwatch.html
