### ISSUE TITLE
$__timeFilter ?

### ISSUE THREAD

**Issue by basicbrownie** [mtanda/grafana-aws-athena-datasource#47]
apologies for lack of understanding. i have data in s3/athena and what to filter a query using the calendar variables dropdown.

select * from table where $__timeFilter(eventtime) limit 10;

but i get this error, InvalidRequestException: line 4:9: mismatched input '$'. Expecting: <expression> status code: 400, request id: 

I usually do this in regular grafana but not getting it to work with this plugin.. do i need to make a new variable in order to pull the calendar eventime interval i want to look at? if so how? 

thank you in advance for help

**Comment by mtanda** [comment]
`$__timeFilter` is datasource specific feature, some datasource (e.g. mysql) support it.
But, athena datasource doesn't support it.

One of workaround is using time range global variables.
https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__from-and-__to

**Comment by basicbrownie** [comment]
You are amazing man. thank you so much. for reference for anyone else. WHERE eventtime between '${__from:date}' and '${__to:date}'. ありがとうございます
